
- name: Configurar integración LDAP en GitLab
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    marker: "# {mark} ANSIBLE MANAGED LDAP CONFIGURATION"
    block: |
      gitlab_rails['ldap_enabled'] = true
      gitlab_rails['ldap_servers'] = {
        'main' => {
          'label' => 'LDAP',
          'host' => '{{ gitlab_ldap_host }}',
          'port' => {{ gitlab_ldap_port }},
          'uid' => '{{ gitlab_ldap_uid }}',
          'bind_dn' => '{{ gitlab_ldap_bind_dn }}',
          'password' => '{{ gitlab_ldap_password }}',
          'base' => '{{ gitlab_ldap_base }}'
        }
      }
  when: gitlab_ldap_enabled

- name: Reconfigurar GitLab después de LDAP
  command: gitlab-ctl reconfigure
  when: gitlab_ldap_enabled
